repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: insert-license-js
        files: '(src/).*\.(ts|js|css|scss)$'
        args:
          - --use-current-year
          - --license-filepath
          - .license_header_template.txt
          - --comment-style
          - /*| *| */
      - id: insert-license
        name: insert-license-html
        files: '(src/).*\.html$'
        args:
          - --use-current-year
          - --license-filepath
          - .license_header_template.txt
          - --comment-style
          - <!--|  ~|  -->
  - repo: local
    hooks:
      - id: lint
        name: run linter
        entry: npm run lint
        pass_filenames: false
        language: node