/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    preflight: false,
  },
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        background: "var(--mat-sys-background)",
        surface: "var(--mat-sys-surface)",
        "surface-container": "var(--mat-sys-surface-container)",
        "surface-dim": "var(--mat-sys-surface-dim)",
        "on-background": "var(--mat-sys-on-background)",
        "on-surface": "var(--mat-sys-on-surface)",
        "on-surface-variant": "var(--mat-sys-on-surface-variant)",
        outline: "var(--mat-sys-outline)",
        "outline-variant": "var(--mat-sys-outline-variant)",
        primary: "var(--mat-sys-primary)",
        "primary-container": "var(--mat-sys-primary-container)",
        "inverse-primary": "var(--mat-sys-inverse-primary)",
        "on-primary": "var(--mat-sys-on-primary)",
        "on-primary-container": "var(--mat-sys-on-primary-container)",
        secondary: "var(--mat-sys-secondary)",
        "secondary-container": "var(--mat-sys-secondary-container)",
        "on-secondary": "var(--mat-sys-on-secondary)",
        "on-secondary-container": "var(--mat-sys-on-secondary-container)",
        tertiary: "var(--mat-sys-tertiary)",
        "tertiary-container": "var(--mat-sys-tertiary-container)",
        "on-tertiary": "var(--mat-sys-on-tertiary)",
        "on-tertiary-container": "var(--mat-sys-on-tertiary-container)",
        error: "var(--mat-sys-error)",
        "error-container": "var(--mat-sys-error-container)",
        "on-error": "var(--mat-sys-on-error)",
        "on-error-container": "var(--mat-sys-on-error-container)",
      },
    },
  },
  plugins: [],
};
